//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcommerceDatabaseEntities : DbContext
    {
        public EcommerceDatabaseEntities()
            : base("name=EcommerceDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Order_tbl> Order_tbl { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<User_tbl> User_tbl { get; set; }
      
    }
}
